// This file is autogenerated.
#ifndef __XSCOPE_PROBES_H__
#define __XSCOPE_PROBES_H__
#define MEDIA_CLOCK_WORDLEN (-1)
#define MEDIA_CLOCK_IERROR (-1)
#define MEDIA_CLOCK_PERROR (-1)
#define LISTENER_1722_SEQ_NUM_MISMATCH (-1)
#endif // __XSCOPE_PROBES_H__
